version: '3.8'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    volumes:
      - nats-data:/data
    command: "--jetstream --store_dir=/data"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microservices_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npx prisma migrate deploy --schema libs/common/prisma/schema.prisma && node dist/apps/gateway/main.js"
    ports:
      - "3000:3000"
    environment:
      NATS_URL: nats://nats:4222
      DATABASE_URL: postgresql://user:password@postgres:5432/microservices_db?schema=public
      GATEWAY_PORT: 3000
    depends_on:
      - nats
      - postgres
    networks:
      - app-network

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npx prisma migrate deploy --schema libs/common/prisma/schema.prisma && node dist/apps/user-service/main.js"
    environment:
      NATS_URL: nats://nats:4222
      DATABASE_URL: postgresql://user:password@postgres:5432/microservices_db?schema=public
    depends_on:
      - nats
      - postgres
    networks:
      - app-network

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npx prisma migrate deploy --schema libs/common/prisma/schema.prisma && node dist/apps/product-service/main.js"
    environment:
      NATS_URL: nats://nats:4222
      DATABASE_URL: postgresql://user:password@postgres:5432/microservices_db?schema=public
    depends_on:
      - nats
      - postgres
    networks:
      - app-network

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npx prisma migrate deploy --schema libs/common/prisma/schema.prisma && node dist/apps/order-service/main.js"
    environment:
      NATS_URL: nats://nats:4222
      DATABASE_URL: postgresql://user:password@postgres:5432/microservices_db?schema=public
    depends_on:
      - nats
      - postgres
    networks:
      - app-network

volumes:
  nats-data:
  postgres-data:

networks:
  app-network:
    driver: bridge