FROM node:20-alpine

WORKDIR /app
COPY package*.json ./
COPY nest-cli.json ./
COPY tsconfig.json ./
COPY libs/ ./libs/
COPY apps/ ./apps/

RUN npm install

# Generate Prisma client (still needed at runtime)
RUN npx prisma generate --schema libs/common/prisma/schema.prisma

EXPOSE 3000

# Command will be overridden in docker-compose.yml per service
CMD ["npm", "run", "start:dev"]
