auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2025-03-22  # Use today's date
      store: tsdb  # Switch to tsdb
      object_store: filesystem
      schema: v13  # Update to v13
      index:
        prefix: index_
        period: 24h

limits_config:
  volume_enabled: true
  max_query_series: 5000
  max_query_length: 721h
  allow_structured_metadata: true  # Enable Structured Metadata