global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:3000']
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3000']
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3000']
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3000']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert-rules.yml"
